displayName=Limit Keeper
author=ShepFX
description=Tracks how much of each item's 4 hour Grand Exchange buy limit you have used
tags=ge,grand,exchange,buy,limit,trade,flip,merch
version=1.0
plugins=net.cukservers.limitkeeper.LimitKeeperPlugin
build=standard
